"""ValueMap dataclass and utilities for spatial cost/affordance maps."""

from dataclasses import dataclass, field
from typing import Optional

import numpy as np
from scipy.ndimage import distance_transform_edt, gaussian_filter

from voxposer.calvin_interface import pc2voxel
from voxposer.utils import normalize_map


@dataclass
class ValueMap:
    """3D voxel value map with workspace metadata.

    Stores affordance (target) and avoidance (obstacle) maps generated by the
    LLM composer, plus precomputed gradient fields for efficient steering
    during diffusion denoising.
    """

    affordance: np.ndarray  # (M, M, M) target regions, higher = more desirable
    workspace_bounds_min: np.ndarray  # (3,) world frame meters
    workspace_bounds_max: np.ndarray  # (3,) world frame meters
    map_size: int
    instruction: str

    avoidance: Optional[np.ndarray] = None  # (M, M, M) obstacle regions

    # Precomputed gradient fields (set by precompute_gradients)
    _cost_map: Optional[np.ndarray] = field(default=None, repr=False)
    _grad_x: Optional[np.ndarray] = field(default=None, repr=False)
    _grad_y: Optional[np.ndarray] = field(default=None, repr=False)
    _grad_z: Optional[np.ndarray] = field(default=None, repr=False)
    # Sparse mask of LLM-set target voxels before EDT smoothing (for visualization)
    _raw_affordance: Optional[np.ndarray] = field(default=None, repr=False)

    def smooth(self, obstacle_sigma: float = 3.0):
        """Apply VoxPoser-style post-processing to sparse LLM-generated maps.

        Affordance: Euclidean distance transform creates a smooth gradient field
        radiating from the target voxel(s). Avoidance: Gaussian blur creates
        soft penalty regions from binary obstacle masks.
        """
        if self.affordance.max() > 0:
            # Save sparse boolean mask before smoothing (used by visualizer for target markers)
            self._raw_affordance = (self.affordance > 0).astype(np.float32)
            # EDT on inverted binary mask: distance from each voxel to nearest target
            edt = distance_transform_edt(1 - self._raw_affordance)
            # Invert so target has highest value, far away has lowest
            self.affordance = edt.max() - edt
            self.affordance = normalize_map(self.affordance)

        if self.avoidance is not None and self.avoidance.max() > 0:
            self.avoidance = gaussian_filter(
                self.avoidance.astype(float), sigma=obstacle_sigma
            )
            self.avoidance = normalize_map(self.avoidance)

    def to_cost_map(self, avoidance_weight: float = 1.0) -> np.ndarray:
        """Combine affordance and avoidance into a single cost map.

        Cost is low where the robot should go (high affordance) and
        high where it should avoid (high avoidance).

        Returns:
            (M, M, M) cost map, lower = more desirable
        """
        # Normalize affordance to [0, 1], invert so high affordance = low cost
        aff_normalized = normalize_map(self.affordance)
        cost = 1.0 - aff_normalized

        if self.avoidance is not None:
            avoid_normalized = normalize_map(self.avoidance)
            cost = cost + avoidance_weight * avoid_normalized

        return cost

    def precompute_gradients(self, avoidance_weight: float = 1.0):
        """Precompute spatial gradient fields of the cost map.

        Called once per episode. The gradient at each voxel points in the
        direction of increasing cost, so negating it gives the direction
        toward lower cost (= higher affordance).

        After calling this, use gradient_at_world_points() for fast lookups.
        """
        self._cost_map = self.to_cost_map(avoidance_weight)
        # np.gradient returns derivatives along each axis
        self._grad_x, self._grad_y, self._grad_z = np.gradient(self._cost_map)

    def gradient_at_world_points(self, world_xyz: np.ndarray) -> np.ndarray:
        """Look up precomputed cost gradient at world-frame 3D points.

        Uses nearest-neighbor interpolation into the voxel grid.

        Args:
            world_xyz: (N, 3) world-frame positions

        Returns:
            (N, 3) gradient vectors pointing toward INCREASING cost.
            Negate these to get the direction toward lower cost.
        """
        if self._grad_x is None:
            self.precompute_gradients()

        world_xyz = np.asarray(world_xyz, dtype=np.float32)
        if world_xyz.ndim == 1:
            world_xyz = world_xyz[np.newaxis, :]

        # Convert to voxel coordinates
        voxel_xyz = pc2voxel(
            world_xyz, self.workspace_bounds_min, self.workspace_bounds_max,
            self.map_size
        )

        # Clamp to valid range
        voxel_xyz = np.clip(voxel_xyz, 0, self.map_size - 1)

        # Look up gradients
        ix = voxel_xyz[:, 0]
        iy = voxel_xyz[:, 1]
        iz = voxel_xyz[:, 2]

        grad = np.stack([
            self._grad_x[ix, iy, iz],
            self._grad_y[ix, iy, iz],
            self._grad_z[ix, iy, iz],
        ], axis=-1)

        return grad

    def affordance_at_world_points(self, world_xyz: np.ndarray) -> np.ndarray:
        """Look up affordance values at world-frame 3D points.

        Args:
            world_xyz: (N, 3) world-frame positions

        Returns:
            (N,) affordance values
        """
        world_xyz = np.asarray(world_xyz, dtype=np.float32)
        if world_xyz.ndim == 1:
            world_xyz = world_xyz[np.newaxis, :]

        voxel_xyz = pc2voxel(
            world_xyz, self.workspace_bounds_min, self.workspace_bounds_max,
            self.map_size
        )
        voxel_xyz = np.clip(voxel_xyz, 0, self.map_size - 1)

        return self.affordance[voxel_xyz[:, 0], voxel_xyz[:, 1], voxel_xyz[:, 2]]

    def voxel_resolution_meters(self) -> np.ndarray:
        """Get the resolution (meters per voxel) along each axis."""
        return (self.workspace_bounds_max - self.workspace_bounds_min) / self.map_size
