# DP3 Debug Training Configuration
# Fast iteration config for local debugging and development

defaults:
  - dp3_calvin

# Override for fast iteration
num_epochs: 10
batch_size: 16  # Smaller batch for faster iteration
val_every: 2
checkpoint_every: 5
num_workers: 2

# Dataset
dataset:
  zarr_path: "${oc.env:CALVIN_ZARR_PATH,/path/to/calvin_debug.zarr}"
  val_ratio: 0.1
  max_train_episodes: 100  # Only use 100 episodes for debugging

# Logging
experiment_name: "dp3_debug_${now:%Y%m%d_%H%M%S}"
use_wandb: false  # Disable WandB for debugging

# Optimization
gradient_accumulation_steps: 1  # No gradient accumulation for faster iteration
